// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoFile/im.proto

package avatar.rain.im.protobuf;

public final class IM {
  private IM() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SendTextToUserC2SOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 toUserId = 1;
    boolean hasToUserId();
    int getToUserId();
    
    // required string message = 2;
    boolean hasMessage();
    String getMessage();
    
    // required .Platform.Model.User user = 3;
    boolean hasUser();
    User getUser();
    UserOrBuilder getUserOrBuilder();

    // optional .Platform.Model.Menu menu = 4;
    boolean hasMenu();
    Menu getMenu();
    MenuOrBuilder getMenuOrBuilder();
  }
  public static final class SendTextToUserC2S extends
      com.google.protobuf.GeneratedMessage
      implements SendTextToUserC2SOrBuilder {
    // Use SendTextToUserC2S.newBuilder() to construct.
    private SendTextToUserC2S(Builder builder) {
      super(builder);
    }
    private SendTextToUserC2S(boolean noInit) {}

    private static final SendTextToUserC2S defaultInstance;
    public static SendTextToUserC2S getDefaultInstance() {
      return defaultInstance;
    }

    public SendTextToUserC2S getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IM.internal_static_Platform_Model_SendTextToUserC2S_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IM.internal_static_Platform_Model_SendTextToUserC2S_fieldAccessorTable;
    }

    private int bitField0_;
    // required int32 toUserId = 1;
    public static final int TOUSERID_FIELD_NUMBER = 1;
    private int toUserId_;
    public boolean hasToUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getToUserId() {
      return toUserId_;
    }

    // required string message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private Object message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          message_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .Platform.Model.User user = 3;
    public static final int USER_FIELD_NUMBER = 3;
    private User user_;
    public boolean hasUser() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public User getUser() {
      return user_;
    }
    public UserOrBuilder getUserOrBuilder() {
      return user_;
    }

    // optional .Platform.Model.Menu menu = 4;
    public static final int MENU_FIELD_NUMBER = 4;
    private Menu menu_;
    public boolean hasMenu() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public Menu getMenu() {
      return menu_;
    }
    public MenuOrBuilder getMenuOrBuilder() {
      return menu_;
    }

    private void initFields() {
      toUserId_ = 0;
      message_ = "";
      user_ = User.getDefaultInstance();
      menu_ = Menu.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasToUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUser().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasMenu()) {
        if (!getMenu().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, toUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, user_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, menu_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, toUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, user_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, menu_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SendTextToUserC2S parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static SendTextToUserC2S parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static SendTextToUserC2S parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static SendTextToUserC2S parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static SendTextToUserC2S parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static SendTextToUserC2S parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static SendTextToUserC2S parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static SendTextToUserC2S parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static SendTextToUserC2S parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static SendTextToUserC2S parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SendTextToUserC2S prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SendTextToUserC2SOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IM.internal_static_Platform_Model_SendTextToUserC2S_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IM.internal_static_Platform_Model_SendTextToUserC2S_fieldAccessorTable;
      }

      // Construct using avatar.rain.im.protobuf.IM.SendTextToUserC2S.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserFieldBuilder();
          getMenuFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        toUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (userBuilder_ == null) {
          user_ = User.getDefaultInstance();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (menuBuilder_ == null) {
          menu_ = Menu.getDefaultInstance();
        } else {
          menuBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SendTextToUserC2S.getDescriptor();
      }

      public SendTextToUserC2S getDefaultInstanceForType() {
        return SendTextToUserC2S.getDefaultInstance();
      }

      public SendTextToUserC2S build() {
        SendTextToUserC2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private SendTextToUserC2S buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        SendTextToUserC2S result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public SendTextToUserC2S buildPartial() {
        SendTextToUserC2S result = new SendTextToUserC2S(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.toUserId_ = toUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (menuBuilder_ == null) {
          result.menu_ = menu_;
        } else {
          result.menu_ = menuBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SendTextToUserC2S) {
          return mergeFrom((SendTextToUserC2S)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SendTextToUserC2S other) {
        if (other == SendTextToUserC2S.getDefaultInstance()) return this;
        if (other.hasToUserId()) {
          setToUserId(other.getToUserId());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasMenu()) {
          mergeMenu(other.getMenu());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasToUserId()) {

          return false;
        }
        if (!hasMessage()) {

          return false;
        }
        if (!hasUser()) {

          return false;
        }
        if (!getUser().isInitialized()) {

          return false;
        }
        if (hasMenu()) {
          if (!getMenu().isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              toUserId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              message_ = input.readBytes();
              break;
            }
            case 26: {
              User.Builder subBuilder = User.newBuilder();
              if (hasUser()) {
                subBuilder.mergeFrom(getUser());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setUser(subBuilder.buildPartial());
              break;
            }
            case 34: {
              Menu.Builder subBuilder = Menu.newBuilder();
              if (hasMenu()) {
                subBuilder.mergeFrom(getMenu());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMenu(subBuilder.buildPartial());
              break;
            }
          }
        }
      }

      private int bitField0_;

      // required int32 toUserId = 1;
      private int toUserId_ ;
      public boolean hasToUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getToUserId() {
        return toUserId_;
      }
      public Builder setToUserId(int value) {
        bitField0_ |= 0x00000001;
        toUserId_ = value;
        onChanged();
        return this;
      }
      public Builder clearToUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        toUserId_ = 0;
        onChanged();
        return this;
      }

      // required string message = 2;
      private Object message_ = "";
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      void setMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        message_ = value;
        onChanged();
      }

      // required .Platform.Model.User user = 3;
      private User user_ = User.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          User, User.Builder, UserOrBuilder> userBuilder_;
      public boolean hasUser() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public User getUser() {
        if (userBuilder_ == null) {
          return user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      public Builder setUser(User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setUser(
          User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeUser(User value) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              user_ != User.getDefaultInstance()) {
            user_ =
              User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = User.getDefaultInstance();
          onChanged();
        } else {
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public User.Builder getUserBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      public UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          User, User.Builder, UserOrBuilder>
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              User, User.Builder, UserOrBuilder>(
                  user_,
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      // optional .Platform.Model.Menu menu = 4;
      private Menu menu_ = Menu.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Menu, Menu.Builder, MenuOrBuilder> menuBuilder_;
      public boolean hasMenu() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public Menu getMenu() {
        if (menuBuilder_ == null) {
          return menu_;
        } else {
          return menuBuilder_.getMessage();
        }
      }
      public Builder setMenu(Menu value) {
        if (menuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          menu_ = value;
          onChanged();
        } else {
          menuBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setMenu(
          Menu.Builder builderForValue) {
        if (menuBuilder_ == null) {
          menu_ = builderForValue.build();
          onChanged();
        } else {
          menuBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeMenu(Menu value) {
        if (menuBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              menu_ != Menu.getDefaultInstance()) {
            menu_ =
              Menu.newBuilder(menu_).mergeFrom(value).buildPartial();
          } else {
            menu_ = value;
          }
          onChanged();
        } else {
          menuBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearMenu() {
        if (menuBuilder_ == null) {
          menu_ = Menu.getDefaultInstance();
          onChanged();
        } else {
          menuBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public Menu.Builder getMenuBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getMenuFieldBuilder().getBuilder();
      }
      public MenuOrBuilder getMenuOrBuilder() {
        if (menuBuilder_ != null) {
          return menuBuilder_.getMessageOrBuilder();
        } else {
          return menu_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Menu, Menu.Builder, MenuOrBuilder>
          getMenuFieldBuilder() {
        if (menuBuilder_ == null) {
          menuBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Menu, Menu.Builder, MenuOrBuilder>(
                  menu_,
                  getParentForChildren(),
                  isClean());
          menu_ = null;
        }
        return menuBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Platform.Model.SendTextToUserC2S)
    }

    static {
      defaultInstance = new SendTextToUserC2S(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.Model.SendTextToUserC2S)
  }

  public interface SendTextToUserS2COrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool status = 1;
    boolean hasStatus();
    boolean getStatus();
  }
  public static final class SendTextToUserS2C extends
      com.google.protobuf.GeneratedMessage
      implements SendTextToUserS2COrBuilder {
    // Use SendTextToUserS2C.newBuilder() to construct.
    private SendTextToUserS2C(Builder builder) {
      super(builder);
    }
    private SendTextToUserS2C(boolean noInit) {}

    private static final SendTextToUserS2C defaultInstance;
    public static SendTextToUserS2C getDefaultInstance() {
      return defaultInstance;
    }

    public SendTextToUserS2C getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IM.internal_static_Platform_Model_SendTextToUserS2C_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IM.internal_static_Platform_Model_SendTextToUserS2C_fieldAccessorTable;
    }

    private int bitField0_;
    // required bool status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private boolean status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getStatus() {
      return status_;
    }

    private void initFields() {
      status_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SendTextToUserS2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static SendTextToUserS2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static SendTextToUserS2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static SendTextToUserS2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static SendTextToUserS2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static SendTextToUserS2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static SendTextToUserS2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static SendTextToUserS2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static SendTextToUserS2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static SendTextToUserS2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SendTextToUserS2C prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SendTextToUserS2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IM.internal_static_Platform_Model_SendTextToUserS2C_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IM.internal_static_Platform_Model_SendTextToUserS2C_fieldAccessorTable;
      }

      // Construct using avatar.rain.im.protobuf.IM.SendTextToUserS2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SendTextToUserS2C.getDescriptor();
      }

      public SendTextToUserS2C getDefaultInstanceForType() {
        return SendTextToUserS2C.getDefaultInstance();
      }

      public SendTextToUserS2C build() {
        SendTextToUserS2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private SendTextToUserS2C buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        SendTextToUserS2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public SendTextToUserS2C buildPartial() {
        SendTextToUserS2C result = new SendTextToUserS2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SendTextToUserS2C) {
          return mergeFrom((SendTextToUserS2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SendTextToUserS2C other) {
        if (other == SendTextToUserS2C.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStatus()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readBool();
              break;
            }
          }
        }
      }

      private int bitField0_;

      // required bool status = 1;
      private boolean status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getStatus() {
        return status_;
      }
      public Builder setStatus(boolean value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.Model.SendTextToUserS2C)
    }

    static {
      defaultInstance = new SendTextToUserS2C(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.Model.SendTextToUserS2C)
  }

  public interface UserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    boolean hasId();
    String getId();

    // required string account = 2;
    boolean hasAccount();
    String getAccount();

    // required string pwd = 3;
    boolean hasPwd();
    String getPwd();

    // required int64 createTime = 4;
    boolean hasCreateTime();
    long getCreateTime();

    // required int32 status = 6;
    boolean hasStatus();
    int getStatus();
  }
  public static final class User extends
      com.google.protobuf.GeneratedMessage
      implements UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(Builder builder) {
      super(builder);
    }
    private User(boolean noInit) {}

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IM.internal_static_Platform_Model_User_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IM.internal_static_Platform_Model_User_fieldAccessorTable;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string account = 2;
    public static final int ACCOUNT_FIELD_NUMBER = 2;
    private Object account_;
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getAccount() {
      Object ref = account_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          account_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccountBytes() {
      Object ref = account_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string pwd = 3;
    public static final int PWD_FIELD_NUMBER = 3;
    private Object pwd_;
    public boolean hasPwd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPwd() {
      Object ref = pwd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pwd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPwdBytes() {
      Object ref = pwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 createTime = 4;
    public static final int CREATETIME_FIELD_NUMBER = 4;
    private long createTime_;
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getCreateTime() {
      return createTime_;
    }

    // required int32 status = 6;
    public static final int STATUS_FIELD_NUMBER = 6;
    private int status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getStatus() {
      return status_;
    }

    private void initFields() {
      id_ = "";
      account_ = "";
      pwd_ = "";
      createTime_ = 0L;
      status_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPwd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPwdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, createTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccountBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPwdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, createTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IM.internal_static_Platform_Model_User_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IM.internal_static_Platform_Model_User_fieldAccessorTable;
      }

      // Construct using avatar.rain.im.protobuf.IM.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        pwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return User.getDescriptor();
      }

      public User getDefaultInstanceForType() {
        return User.getDefaultInstance();
      }

      public User build() {
        User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private User buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public User buildPartial() {
        User result = new User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pwd_ = pwd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof User) {
          return mergeFrom((User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(User other) {
        if (other == User.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        if (other.hasPwd()) {
          setPwd(other.getPwd());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {

          return false;
        }
        if (!hasAccount()) {

          return false;
        }
        if (!hasPwd()) {

          return false;
        }
        if (!hasCreateTime()) {

          return false;
        }
        if (!hasStatus()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              account_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              pwd_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              createTime_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              status_ = input.readInt32();
              break;
            }
          }
        }
      }

      private int bitField0_;

      // required string id = 1;
      private Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }

      // required string account = 2;
      private Object account_ = "";
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getAccount() {
        Object ref = account_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccount(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      void setAccount(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        account_ = value;
        onChanged();
      }

      // required string pwd = 3;
      private Object pwd_ = "";
      public boolean hasPwd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPwd() {
        Object ref = pwd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pwd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPwd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pwd_ = value;
        onChanged();
        return this;
      }
      public Builder clearPwd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pwd_ = getDefaultInstance().getPwd();
        onChanged();
        return this;
      }
      void setPwd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        pwd_ = value;
        onChanged();
      }

      // required int64 createTime = 4;
      private long createTime_ ;
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getCreateTime() {
        return createTime_;
      }
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000008;
        createTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      // required int32 status = 6;
      private int status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getStatus() {
        return status_;
      }
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000010;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000010);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Platform.Model.User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.Model.User)
  }

  public interface MenuOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    boolean hasId();
    String getId();

    // required int64 createTime = 2;
    boolean hasCreateTime();
    long getCreateTime();

    // required string pwd = 3;
    boolean hasPwd();
    String getPwd();

    // required .Platform.Model.Org org = 4;
    boolean hasOrg();
    Org getOrg();
    OrgOrBuilder getOrgOrBuilder();
  }
  public static final class Menu extends
      com.google.protobuf.GeneratedMessage
      implements MenuOrBuilder {
    // Use Menu.newBuilder() to construct.
    private Menu(Builder builder) {
      super(builder);
    }
    private Menu(boolean noInit) {}

    private static final Menu defaultInstance;
    public static Menu getDefaultInstance() {
      return defaultInstance;
    }

    public Menu getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IM.internal_static_Platform_Model_Menu_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IM.internal_static_Platform_Model_Menu_fieldAccessorTable;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 createTime = 2;
    public static final int CREATETIME_FIELD_NUMBER = 2;
    private long createTime_;
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getCreateTime() {
      return createTime_;
    }

    // required string pwd = 3;
    public static final int PWD_FIELD_NUMBER = 3;
    private Object pwd_;
    public boolean hasPwd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPwd() {
      Object ref = pwd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pwd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPwdBytes() {
      Object ref = pwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .Platform.Model.Org org = 4;
    public static final int ORG_FIELD_NUMBER = 4;
    private Org org_;
    public boolean hasOrg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public Org getOrg() {
      return org_;
    }
    public OrgOrBuilder getOrgOrBuilder() {
      return org_;
    }

    private void initFields() {
      id_ = "";
      createTime_ = 0L;
      pwd_ = "";
      org_ = Org.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPwd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getOrg().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, createTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPwdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, org_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, createTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPwdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, org_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Menu parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Menu parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Menu parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Menu parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Menu parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Menu parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Menu parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Menu parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Menu parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Menu parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Menu prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MenuOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IM.internal_static_Platform_Model_Menu_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IM.internal_static_Platform_Model_Menu_fieldAccessorTable;
      }

      // Construct using avatar.rain.im.protobuf.IM.Menu.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOrgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        pwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (orgBuilder_ == null) {
          org_ = Org.getDefaultInstance();
        } else {
          orgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Menu.getDescriptor();
      }

      public Menu getDefaultInstanceForType() {
        return Menu.getDefaultInstance();
      }

      public Menu build() {
        Menu result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private Menu buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Menu result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public Menu buildPartial() {
        Menu result = new Menu(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.createTime_ = createTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pwd_ = pwd_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (orgBuilder_ == null) {
          result.org_ = org_;
        } else {
          result.org_ = orgBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Menu) {
          return mergeFrom((Menu)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Menu other) {
        if (other == Menu.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasPwd()) {
          setPwd(other.getPwd());
        }
        if (other.hasOrg()) {
          mergeOrg(other.getOrg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {

          return false;
        }
        if (!hasCreateTime()) {

          return false;
        }
        if (!hasPwd()) {

          return false;
        }
        if (!hasOrg()) {

          return false;
        }
        if (!getOrg().isInitialized()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              createTime_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              pwd_ = input.readBytes();
              break;
            }
            case 34: {
              Org.Builder subBuilder = Org.newBuilder();
              if (hasOrg()) {
                subBuilder.mergeFrom(getOrg());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setOrg(subBuilder.buildPartial());
              break;
            }
          }
        }
      }

      private int bitField0_;

      // required string id = 1;
      private Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }

      // required int64 createTime = 2;
      private long createTime_ ;
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getCreateTime() {
        return createTime_;
      }
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000002;
        createTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      // required string pwd = 3;
      private Object pwd_ = "";
      public boolean hasPwd() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPwd() {
        Object ref = pwd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pwd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPwd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pwd_ = value;
        onChanged();
        return this;
      }
      public Builder clearPwd() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pwd_ = getDefaultInstance().getPwd();
        onChanged();
        return this;
      }
      void setPwd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        pwd_ = value;
        onChanged();
      }

      // required .Platform.Model.Org org = 4;
      private Org org_ = Org.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Org, Org.Builder, OrgOrBuilder> orgBuilder_;
      public boolean hasOrg() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public Org getOrg() {
        if (orgBuilder_ == null) {
          return org_;
        } else {
          return orgBuilder_.getMessage();
        }
      }
      public Builder setOrg(Org value) {
        if (orgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          org_ = value;
          onChanged();
        } else {
          orgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setOrg(
          Org.Builder builderForValue) {
        if (orgBuilder_ == null) {
          org_ = builderForValue.build();
          onChanged();
        } else {
          orgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeOrg(Org value) {
        if (orgBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              org_ != Org.getDefaultInstance()) {
            org_ =
              Org.newBuilder(org_).mergeFrom(value).buildPartial();
          } else {
            org_ = value;
          }
          onChanged();
        } else {
          orgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearOrg() {
        if (orgBuilder_ == null) {
          org_ = Org.getDefaultInstance();
          onChanged();
        } else {
          orgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public Org.Builder getOrgBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getOrgFieldBuilder().getBuilder();
      }
      public OrgOrBuilder getOrgOrBuilder() {
        if (orgBuilder_ != null) {
          return orgBuilder_.getMessageOrBuilder();
        } else {
          return org_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Org, Org.Builder, OrgOrBuilder>
          getOrgFieldBuilder() {
        if (orgBuilder_ == null) {
          orgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Org, Org.Builder, OrgOrBuilder>(
                  org_,
                  getParentForChildren(),
                  isClean());
          org_ = null;
        }
        return orgBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Platform.Model.Menu)
    }

    static {
      defaultInstance = new Menu(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.Model.Menu)
  }

  public interface OrgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string id = 1;
    boolean hasId();
    String getId();

    // required string pwd = 2;
    boolean hasPwd();
    String getPwd();
  }
  public static final class Org extends
      com.google.protobuf.GeneratedMessage
      implements OrgOrBuilder {
    // Use Org.newBuilder() to construct.
    private Org(Builder builder) {
      super(builder);
    }
    private Org(boolean noInit) {}

    private static final Org defaultInstance;
    public static Org getDefaultInstance() {
      return defaultInstance;
    }

    public Org getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IM.internal_static_Platform_Model_Org_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IM.internal_static_Platform_Model_Org_fieldAccessorTable;
    }

    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string pwd = 2;
    public static final int PWD_FIELD_NUMBER = 2;
    private Object pwd_;
    public boolean hasPwd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPwd() {
      Object ref = pwd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          pwd_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPwdBytes() {
      Object ref = pwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        pwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      pwd_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPwd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPwdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPwdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Org parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Org parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Org parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Org parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Org parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Org parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Org parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Org parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Org parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Org parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Org prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements OrgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IM.internal_static_Platform_Model_Org_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IM.internal_static_Platform_Model_Org_fieldAccessorTable;
      }

      // Construct using avatar.rain.im.protobuf.IM.Org.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pwd_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Org.getDescriptor();
      }

      public Org getDefaultInstanceForType() {
        return Org.getDefaultInstance();
      }

      public Org build() {
        Org result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private Org buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Org result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public Org buildPartial() {
        Org result = new Org(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pwd_ = pwd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Org) {
          return mergeFrom((Org)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Org other) {
        if (other == Org.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPwd()) {
          setPwd(other.getPwd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {

          return false;
        }
        if (!hasPwd()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              pwd_ = input.readBytes();
              break;
            }
          }
        }
      }

      private int bitField0_;

      // required string id = 1;
      private Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }

      // required string pwd = 2;
      private Object pwd_ = "";
      public boolean hasPwd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPwd() {
        Object ref = pwd_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          pwd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPwd(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pwd_ = value;
        onChanged();
        return this;
      }
      public Builder clearPwd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pwd_ = getDefaultInstance().getPwd();
        onChanged();
        return this;
      }
      void setPwd(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        pwd_ = value;
        onChanged();
      }

      // @@protoc_insertion_point(builder_scope:Platform.Model.Org)
    }

    static {
      defaultInstance = new Org(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Platform.Model.Org)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_SendTextToUserC2S_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_SendTextToUserC2S_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_SendTextToUserS2C_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_SendTextToUserS2C_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_User_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_Menu_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_Menu_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Platform_Model_Org_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Platform_Model_Org_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022ProtoFile/im.proto\022\016Platform.Model\"~\n\021" +
      "SendTextToUserC2S\022\020\n\010toUserId\030\001 \002(\005\022\017\n\007m" +
      "essage\030\002 \002(\t\022\"\n\004user\030\003 \002(\0132\024.Platform.Mo" +
      "del.User\022\"\n\004menu\030\004 \001(\0132\024.Platform.Model." +
      "Menu\"#\n\021SendTextToUserS2C\022\016\n\006status\030\001 \002(" +
      "\010\"T\n\004User\022\n\n\002id\030\001 \002(\t\022\017\n\007account\030\002 \002(\t\022\013" +
      "\n\003pwd\030\003 \002(\t\022\022\n\ncreateTime\030\004 \002(\003\022\016\n\006statu" +
      "s\030\006 \002(\005\"U\n\004Menu\022\n\n\002id\030\001 \002(\t\022\022\n\ncreateTim" +
      "e\030\002 \002(\003\022\013\n\003pwd\030\003 \002(\t\022 \n\003org\030\004 \002(\0132\023.Plat" +
      "form.Model.Org\"\036\n\003Org\022\n\n\002id\030\001 \002(\t\022\013\n\003pwd",
      "\030\002 \002(\tB\035\n\027avatar.rain.im.protobufB\002IM"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Platform_Model_SendTextToUserC2S_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Platform_Model_SendTextToUserC2S_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_Model_SendTextToUserC2S_descriptor,
              new String[] { "ToUserId", "Message", "User", "Menu", },
              SendTextToUserC2S.class,
              SendTextToUserC2S.Builder.class);
          internal_static_Platform_Model_SendTextToUserS2C_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Platform_Model_SendTextToUserS2C_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_Model_SendTextToUserS2C_descriptor,
              new String[] { "Status", },
              SendTextToUserS2C.class,
              SendTextToUserS2C.Builder.class);
          internal_static_Platform_Model_User_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Platform_Model_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_Model_User_descriptor,
              new String[] { "Id", "Account", "Pwd", "CreateTime", "Status", },
              User.class,
              User.Builder.class);
          internal_static_Platform_Model_Menu_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Platform_Model_Menu_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_Model_Menu_descriptor,
              new String[] { "Id", "CreateTime", "Pwd", "Org", },
              Menu.class,
              Menu.Builder.class);
          internal_static_Platform_Model_Org_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_Platform_Model_Org_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Platform_Model_Org_descriptor,
              new String[] { "Id", "Pwd", },
              Org.class,
              Org.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
